#!/bin/sh

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Hooks for loading smartcard reading software into the initramfs

# Install directories needed by smartcard reading daemon, command, and
# key-script
for dir in etc/opensc usr/lib/pcsc var/run tmp ; do
    if [ ! -d ${DESTDIR}/${dir} ] ; then mkdir -p ${DESTDIR}/${dir} ; fi
done

# Install pcscd daemon, drivers, conf file, and include libgcc as well since
# pcscd utilizes pthread_cancel
copy_exec /usr/sbin/pcscd /sbin
copy_exec /bin/hexdump /bin

cp -r /usr/lib/pcsc ${DESTDIR}/usr/lib
cp -r /etc/reader.conf.d ${DESTDIR}/etc
cp /etc/libccid_Info.plist ${DESTDIR}/etc

# Install opensc commands and conf file
copy_exec /usr/bin/opensc-tool /bin
cp /etc/opensc/opensc.conf ${DESTDIR}/etc/opensc

# Install other required utilities
copy_exec /bin/grep /bin
copy_exec /bin/mv /bin
copy_exec /bin/rm /bin
copy_exec /usr/bin/xxd /bin
copy_exec /usr/bin/killall /bin

# Main scripts

# Libraries
cp /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 ${DESTDIR}/lib
cp /usr/lib/x86_64-linux-gnu/libpcsclite.so.1 ${DESTDIR}/lib
cp /usr/lib/x86_64-linux-gnu/libusb-1.0.so.0 ${DESTDIR}/lib
